# Keras Basics

Section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.


In [1]:
import numpy as np

## Dataset

We will use the Bank Authentication Data Set to start off with. This data set consists of various image features derived from images that had 400 x 400 pixels. You should note **the data itself that we will be using ARE NOT ACTUAL IMAGES**, they are **features** of images. In the next lecture we will cover grabbing and working with image data with Keras. This notebook focuses on learning the basics of building a neural network with Keras.

_____
More info on the data set:

https://archive.ics.uci.edu/ml/datasets/banknote+authentication

Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization, an industrial camera usually used for print inspection was used. The final images have 400x 400 pixels. Due to the object lens and distance to the investigated object gray-scale pictures with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images.


Attribute Information:

1. variance of Wavelet Transformed image (continuous) 
2. skewness of Wavelet Transformed image (continuous) 
3. curtosis of Wavelet Transformed image (continuous) 
4. entropy of image (continuous) 
5. class (integer) 

## Reading in the Data Set

We've already have the dataset, its in the DATA folder. So let's open it up. 

In [2]:
from numpy import genfromtxt
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

## Split the Data into Training and Test

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now.

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [12]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [13]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [14]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler_object = MinMaxScaler()

In [17]:
scaler_object.fit(X_train)

MinMaxScaler()

In [18]:
scaled_X_train = scaler_object.transform(X_train)

In [19]:
scaled_X_test = scaler_object.transform(X_test)

Ok, now we have the data scaled!

In [20]:
X_train.max()

np.float64(17.9274)

In [21]:
scaled_X_train.max()

np.float64(1.0000000000000002)

In [22]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [23]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

## Building the Network with Keras

Let's build a simple neural network!

In [24]:
from keras.models import Sequential
from keras.layers import Dense

2024-12-29 21:25:24.851457: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-29 21:25:26.691256: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-29 21:25:27.517651: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1735487728.340687   11485 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1735487728.576132   11485 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-29 21:25:31.295412: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [25]:
# Creates model
model = Sequential()
# 8 Neurons, expects input of 4 features. 
# Play around with the number of neurons!!
model.add(Dense(4, input_dim=4, activation='relu'))
# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
model.add(Dense(8, activation='relu'))
# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))

/home/vpsr/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2024-12-29 21:25:51.764902: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


### Compile Model

In [26]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Fit (Train) the Model

In [27]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=50, verbose=2)

Epoch 1/50
29/29 - 3s - 115ms/step - accuracy: 0.5495 - loss: 0.6667
Epoch 2/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: 0.6601
Epoch 3/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: 0.6535
Epoch 4/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: 0.6461
Epoch 5/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: 0.6384
Epoch 6/50
29/29 - 0s - 2ms/step - accuracy: 0.5517 - loss: 0.6288
Epoch 7/50
29/29 - 0s - 2ms/step - accuracy: 0.5756 - loss: 0.6184
Epoch 8/50
29/29 - 0s - 3ms/step - accuracy: 0.6213 - loss: 0.6067
Epoch 9/50
29/29 - 0s - 2ms/step - accuracy: 0.6605 - loss: 0.5936
Epoch 10/50
29/29 - 0s - 2ms/step - accuracy: 0.7018 - loss: 0.5792
Epoch 11/50
29/29 - 0s - 2ms/step - accuracy: 0.7312 - loss: 0.5645
Epoch 12/50
29/29 - 0s - 2ms/step - accuracy: 0.7671 - loss: 0.5494
Epoch 13/50
29/29 - 0s - 2ms/step - accuracy: 0.7824 - loss: 0.5333
Epoch 14/50
29/29 - 0s - 2ms/step - accuracy: 0.8009 - loss: 0.5174
Epoch 15/50
29/29 - 0s - 3ms/step - accuracy: 0.8324 - 

## Predicting New Unseen Data

Let's see how we did by predicting on **new data**. Remember, our model has **never** seen the test data that we scaled previously! This process is the exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed .

In [28]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [29]:
# Spits out probabilities by default.
# model.predict(scaled_X_test)

In [32]:
model.predict(scaled_X_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


array([[3.23221758e-02],
       [4.93747592e-01],
       [2.71504849e-01],
       [2.64352970e-02],
       [3.71839032e-02],
       [1.07321274e-02],
       [1.15275860e-01],
       [6.11758698e-03],
       [1.96697507e-02],
       [6.00218959e-02],
       [6.13302767e-01],
       [9.26804543e-01],
       [5.62832616e-02],
       [7.91907430e-01],
       [3.25054526e-01],
       [3.84690046e-01],
       [9.12776470e-01],
       [9.25194144e-01],
       [9.70861435e-01],
       [7.94026196e-01],
       [1.86326057e-02],
       [2.94536240e-02],
       [8.29417050e-01],
       [1.27317710e-02],
       [9.92644072e-01],
       [1.37235457e-02],
       [5.71354944e-03],
       [8.43531489e-01],
       [5.77657425e-04],
       [1.92984368e-03],
       [8.52014780e-01],
       [4.72363494e-02],
       [7.56817758e-02],
       [9.93191957e-01],
       [9.87318993e-01],
       [5.70770539e-03],
       [5.79535961e-01],
       [8.53393197e-01],
       [9.35709536e-01],
       [3.98589745e-02],


# Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision.

In [33]:
model.metrics_names

['loss', 'compile_metrics']

In [34]:
model.evaluate(x=scaled_X_test,y=y_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9638 - loss: 0.1320


[0.11233899742364883, 0.9757174253463745]

In [35]:
from sklearn.metrics import confusion_matrix,classification_report

In [37]:
predictions = model.predict(scaled_X_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [ ]:
confusion_matrix(y_test,predictions)

In [ ]:
print(classification_report(y_test,predictions))

## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [40]:
model.save('myfirstmodel.h5')

In [41]:
from keras.models import load_model

In [42]:
newmodel = load_model('myfirstmodel.h5')

In [44]:
newmodel.predict(X_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


array([[6.66275470e-24],
       [2.00863298e-07],
       [1.21652764e-12],
       [1.63184129e-35],
       [7.87420988e-26],
       [8.86183420e-14],
       [2.20440711e-23],
       [9.06323157e-26],
       [1.05395127e-17],
       [4.62100361e-24],
       [9.99934375e-01],
       [1.00000000e+00],
       [1.48350263e-10],
       [1.00000000e+00],
       [2.08761985e-08],
       [8.23322594e-01],
       [9.99998748e-01],
       [9.99995470e-01],
       [1.00000000e+00],
       [1.00000000e+00],
       [6.73693183e-29],
       [1.15336895e-18],
       [1.00000000e+00],
       [1.57849858e-30],
       [1.00000000e+00],
       [2.00420174e-26],
       [9.87972533e-31],
       [1.00000000e+00],
       [0.00000000e+00],
       [4.13457502e-36],
       [1.00000000e+00],
       [2.61222748e-18],
       [1.08851621e-12],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.63880663e-31],
       [9.99196947e-01],
       [9.98251677e-01],
       [1.00000000e+00],
       [1.00202874e-20],


Great! We now know how to preprocess data, train a neural network, and evaluate its classification performance!